apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontrolpanel
  namespace: default
  labels:
    app: kontrolpanel
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kontrolpanel
  template:
    metadata:
      labels:
        app: kontrolpanel
    spec:
      containers:
      - name: kontrolpanel-backend-svc
        image: kontrolpanel-backend-svc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: kontrolpanel-frontend-svc
        image: kontrolpanel-frontend-svc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081