apiVersion: v1
kind: Service
metadata:
  name: kontrolpanel
  namespace: default
  labels:
    app: kontrolpanel
spec:
  type: LoadBalancer
  ports:
  - name: backend-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: frontend-svc
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: kontrolpanel