apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
  - image: grafana/grafana:4.2.0
    name: grafana-core
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    env:
      - name: GF_AUTH_BASIC_ENABLED
        value: "true"
      - name: GF_SECURITY_ADMIN_USER
        value: admin
      - name: GF_SECURITY_ADMIN_PASSWORD
        value: secret
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "false"
    readinessProbe:
      httpGet:
        path: /login
        port: 3000
    volumeMounts:
    - name: grafana-persistent-storage
      mountPath: /var/lib/grafana
  volumes:
  - name: grafana-persistent-storage
    emptyDir: {}